### ISSUE TITLE
CDVMediaStream.m shows 4 warnings

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-plugin-media-stream#12]
### Expected Behaviour
CDVMediaStream.m to not show warnings

### Actual Behaviour
CDVMediaStream.m shows 4 warnings
Method definition for 'pluginLocalizedString:' not found
Method definition for 'receiveImage:' not found
Method definition for 'receiveError' not found
Method definition for 'sendPluginResult:keepResult:' not found

#### Steps to Reproduce
Add the plugin on iOS and open the project on Xcode

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS (any)

#### Cordova CLI version and cordova platform version

    cordova --version                                    any
    cordova platform version ios                  any

#### Plugin version

    cordova plugin version | grep phonegap-plugin-image-capture  1.2.1

**Comment by jcesarmobile** [comment]
It's curious that `receiveImage:`, `receiveError` and `sendPluginResult:keepResult:` are called and the code works.

**Comment by macdonst** [comment]
@jcesarmobile some of these things are used by the Image Capture plugin. With your changed branch can you add it to a project then add phonegap-plugin-image-capture and see if you can still take a picture properly?

**Comment by jcesarmobile** [comment]
Ah, yeah, `receiveError` and `receiveImage` are in `CDVImageCapture.m`.

Do you mean that if I can still take pictures after my changes on https://github.com/phonegap/phonegap-plugin-media-stream/pull/13?

I'll recheck tomorrow, but I think it worked.

**Comment by macdonst** [comment]
@jcesarmobile yeah, if you can double check that taking pictures/video still works that'd be awesome. We are in internal meetings all day today so we'll be unable to get to it.

**Comment by jcesarmobile** [comment]
Ok, will double check tomorrow.
Anyway, the change I did is only for the localizable text and I remember the app still displaying the cancel button, so shouldn't affect the camera button.

**Comment by jcesarmobile** [comment]
@macdonst I confirm that it still works after the changes on #13. But  #13 only fixes one of the 4 warnings I reported. (Method definition for 'pluginLocalizedString:' not found)
