### ISSUE TITLE
Inconsistencies on CDVMediaStream.m class

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-plugin-media-stream#15]
Sorry to delete the template, but I think it doesn't apply.

There are some inconsistencies in CDVMediaStream.m file

You can find this lines:
I think this is wrong, label should be some name for the device, but description is sort of stringification of the native object
`[dict setObject:device.description forKey:@"label"];`

I think this three are wrong, it should be label instead of description
`[videoTracks setObject:@"frontcamera" forKey:@"description"];`

`[videoTracks setObject:@"rearcamera" forKey:@"description"];`

`[audioTracks setObject:device.deviceType forKey:@"description"];`

Also, in last one, `deviceType` is not available on iOS 9, so it should probably return an empty string. Or even better, return `localizedName`

I think this is wrong, kind should be "audio" or "video"
`[dict setObject:device.deviceType forKey:@"kind"];`

I think this two are right
`[videoTracks setObject:@"video" forKey:@"kind"];`

`[audioTracks setObject:@"audio" forKey:@"kind"];`

So the inconsistencies are, sometimes it uses @"description" and others @"label" and they use different values in different places for the same key.

**Comment by maverickmishra** [comment]
Yes, there are some inconsistencies here. We are working on a separate branch `issue3` which incorporates some of these changes as well

**Comment by jcesarmobile** [comment]
I've tried to checkout `issue3` branch to work over those changes and send the PR with a fix there, but unfortunately it crashes on `if([self.camDirection isEqualToString:@"frontcamera"])` with this error:

> 'NSInvalidArgumentException', reason: '-[NSNull isEqualToString:]: unrecognized selector sent to instance 0x39642310'


I'll send the PR against `master`, maybe you can then cherry pick to `issue3` or rebase

**Comment by macdonst** [comment]
@jcesarmobile yeah, feel free to make changes in the `issue3` branch. You should have gotten an email inviting you into the project as a committer.

**Comment by jcesarmobile** [comment]
@macdonst yeah, I received it, but I prefer if somebody review my PRs first

I wrote a comment saying that issue3 branch didn't work and then I deleted it.

The problem is not really issue3 branch, it's that image-capture needs an update as description has been changed to label, I've sent a PR for it
https://github.com/phonegap/phonegap-plugin-image-capture/pull/30

**Comment by macdonst** [comment]
@jcesarmobile yeah, I just wanted to make sure you got the invite and to let you know you can work on the feature branches with us.
