### ISSUE TITLE
webkitAudioContext: stream source be an instance of MediaStream

### ISSUE THREAD

**Issue by nksglns** [phonegap/phonegap-plugin-media-stream#17]
This looks a bit weird. I'm trying to do a tokbox.com (opentok) implementation in cordova using their JS library, but there seems to be a problem. In their library, they're using AudioContext (or webkitAudioContext, if AudioContext is unabailable). I'm getting the following error:

> TypeError: Argument 1 ('mediaStream') to webkitAudioContext.createMediaStreamSource must be an instance of MediaStream

So while looking for alternatives, I tried testing it myself with a small snippet like the one below:
```
navigator.mediaDevices.getUserMedia ({audio: true, video: true})
    .then(function(stream) {
	console.log(stream);
        var audioCtx = new webkitAudioContext();
        var source = audioCtx.createMediaStreamSource(stream);
    })
    .catch(function(err) {
        console.log('Error: ' + err);
    });
```
I added the console.log there to review the resulting stream which - seems - to be an instance of MediaStream indeed, but for some reason createMediaStreamSource still won't accept it. Am I missing something?

**Comment by macdonst** [comment]
@nksglns yeah, our implementation of MediaStream is not a true native implementation of a MediaStream. The idea behind this plugin is to provide the same API as in the web browser so we can pass it to the constructor of the MediaRecorder or ImageCapture API's. 

Sadly, we cannot pass back the raw media stream data like in Safari and even though iOS 11 has this ability in Safari it is not included in the web view.

Does that answer your question?

**Comment by nksglns** [comment]
Yup I thought so already! It just seemed weird that though the type of the object is MediaStream, the audiocontext still requested for a MediaStream.
So, I guess there's no way to convert this MediaStream to (or just use as) an actual MediaStream, right?

**Comment by macdonst** [comment]
@nksglns no, not on iOS at the moment. Hopefully, it will become possible to use the native implementation of `getUserMedia` on iOS soon. For now we just use this shim to get us to a higher level API.

If you want to use opentok you'll need to use a plugin that wraps their native API like this: https://github.com/songz/cordova-plugin-opentok

**Comment by realadamsmith** [comment]
MediaRecorder API Works on Testflight, it just won't work on simulator or on your own device. You must use Testflight to see MediaRecorder API working.
